### ISSUE TITLE
Windows app's deckmaster.log should use windows-style newlines

### ISSUE THREAD

**Issue by rakslice** [Fugiman/deckmaster#12]
The `deckmaster.log` that the deckmaster windows application version 57EA616 writes has Unix-style LF-only newlines, rather than Windows-style CR+LF newlines.

This is awkward because the typical Windows file association for *.log files is Notepad, which just shows the entire log as a single word-wrapped line.

**Comment by rakslice** [comment]
https://stackoverflow.com/a/35556287/60422 :(

**Comment by dmooray** [comment]
Just a small note, next Windows update(planned for autumn) will have Notepad support Unix line endings.

**Comment by Fugiman** [comment]
Yeahhhh I think this is a won't fix for now

**Comment by rakslice** [comment]
Fair enough :D
