### ISSUE TITLE
Cannot close some deck/graveyard preview windows

### ISSUE THREAD

**Issue by Bobert-Brockson** [Fugiman/deckmaster#39]
Occasionally selection of cards within the preview breaks and you cannot close the preview window.

**Comment by Bobert-Brockson** [comment]
Happens on Brian Kibbler's stream.

Perhaps is an interaction with Prime Loot Extension

**Comment by FugiTech** [comment]
Yes, if there's a component extension located anywhere but the very left of the screen it'll interfere with deckmaster. There's nothing I can do to prevent this :(
