### ISSUE TITLE
Deckmaster Does not seem to be working since M20 Release

### ISSUE THREAD

**Issue by RebelliousUno** [Fugiman/deckmaster#45]
Only certain cards appear to be showing up 
for example, watching Day9 stream atm 

His board presence is much greater than shown in the image (https://imgur.com/a/Ge7jcUd)

M20 lands don't appear to show (but other sets lands do)

**Comment by St-Clair** [comment]
This issue is fixed by this force-push

https://github.com/Fugiman/deckmaster/pull/44
